### ISSUE TITLE
"Keeping adjust sleep multiplier" warning shown many times

### ISSUE THREAD

**Issue by Tinter** [rockowitz/ddcutil#427] opened 2024-06-03 18:49 UTC
I am running clight on my system, but I believe this problem really stems from libddcutil. Basically, I get many warnings in my system's journal, it's very noisy.
```Jun 03 20:10:41 nyaarch libddcutil[121362]: dh=Display_Handle[i2c-10: fd=42], Keeping adjusted sleep multiplier 1.00 for SE_POST_WRITE or SE_POST_SAVE_SETTINGS
Jun 03 20:10:41 nyaarch libddcutil[121362]: dh=Display_Handle[i2c-11: fd=42], Keeping adjusted sleep multiplier 1.00 for SE_POST_WRITE or SE_POST_SAVE_SETTINGS
Jun 03 20:10:41 nyaarch libddcutil[121362]: dh=Display_Handle[i2c-9: fd=42], Keeping adjusted sleep multiplier 1.00 for SE_POST_WRITE or SE_POST_SAVE_SETTINGS
Jun 03 20:10:43 nyaarch libddcutil[121362]: dh=Display_Handle[i2c-10: fd=42], Keeping adjusted sleep multiplier 1.00 for SE_POST_WRITE or SE_POST_SAVE_SETTINGS
Jun 03 20:10:43 nyaarch libddcutil[121362]: dh=Display_Handle[i2c-11: fd=42], Keeping adjusted sleep multiplier 1.00 for SE_POST_WRITE or SE_POST_SAVE_SETTINGS
Jun 03 20:10:43 nyaarch libddcutil[121362]: dh=Display_Handle[i2c-9: fd=42], Keeping adjusted sleep multiplier 1.00 for SE_POST_WRITE or SE_POST_SAVE_SETTINGS
Jun 03 20:10:59 nyaarch libddcutil[121362]: dh=Display_Handle[i2c-10: fd=42], Keeping adjusted sleep multiplier 1.00 for SE_POST_WRITE or SE_POST_SAVE_SETTINGS
Jun 03 20:10:59 nyaarch libddcutil[121362]: dh=Display_Handle[i2c-11: fd=42], Keeping adjusted sleep multiplier 1.00 for SE_POST_WRITE or SE_POST_SAVE_SETTINGS
Jun 03 20:10:59 nyaarch libddcutil[121362]: dh=Display_Handle[i2c-9: fd=42], Keeping adjusted sleep multiplier 1.00 for SE_POST_WRITE or SE_POST_SAVE_SETTINGS
Jun 03 20:11:05 nyaarch libddcutil[121362]: dh=Display_Handle[i2c-10: fd=42], Keeping adjusted sleep multiplier 1.00 for SE_POST_WRITE or SE_POST_SAVE_SETTINGS
Jun 03 20:11:05 nyaarch libddcutil[121362]: dh=Display_Handle[i2c-11: fd=42], Keeping adjusted sleep multiplier 1.00 for SE_POST_WRITE or SE_POST_SAVE_SETTINGS
Jun 03 20:11:05 nyaarch libddcutil[121362]: dh=Display_Handle[i2c-9: fd=42], Keeping adjusted sleep multiplier 1.00 for SE_POST_WRITE or SE_POST_SAVE_SETTINGS
Jun 03 20:11:07 nyaarch libddcutil[121362]: dh=Display_Handle[i2c-10: fd=42], Keeping adjusted sleep multiplier 1.00 for SE_POST_WRITE or SE_POST_SAVE_SETTINGS
Jun 03 20:11:07 nyaarch libddcutil[121362]: dh=Display_Handle[i2c-11: fd=42], Keeping adjusted sleep multiplier 1.00 for SE_POST_WRITE or SE_POST_SAVE_SETTINGS
Jun 03 20:11:07 nyaarch libddcutil[121362]: dh=Display_Handle[i2c-9: fd=42], Keeping adjusted sleep multiplier 1.00 for SE_POST_WRITE or SE_POST_SAVE_SETTINGS
```

It looks to be this line printing to the system log https://github.com/rockowitz/ddcutil/blob/c297369c6f4afcd36d825a27d33c6a7d2148ca64/src/base/tuned_sleep.c#L205. However this looks to me like it should've been printed at log level debug, as it appears to be normal operation?

**Comment by rockowitz** [comment] 2024-06-05 17:48
Thank you for the report. 

The issue is addressed in branch 2.1.5-dev, which changes the severity of the log messages in question from WARNING to VERBOSE.

If you are running a version of ddcutil earlier than 2.1.5-dev, you can avoid the messages by altering the cutoff level for messages written to the system log, using option ***--syslog***
~~~
--syslog error
~~~

You may find it more convenient to specify the option in the ddcutil configuration file $USER/.config/ddcutil/ddcutilrc: 
~~~
[global]
options: --syslog error
~~~

**Closed** 2024-08-06 16:58 UTC
Labels: bug, Fixed
